GET http://localhost:3000/

###

GET http://localhost:3000/61dcb92b0172e170462d724f

###

POST http://localhost:3000/
Content-Type: application/json

{
    "name": "Task 4"
}

###

DELETE http://localhost:3000/61dcb92b0172e170462d724f


###

PATCH http://localhost:3000/61dcb92b0172e170462d724f
Content-Type: application/json

{
    "name": "Updated Task"
}

